
let newRecom=[
  {
    "id":297954,
    "cover":"http://localhost:3000/imgs/newRcom1_cover.webp",
    "title":'致不灭的你',
    "tag1":"奇幻旅途",
    "tag2":"猛男落泪",
    "like":"318.4",
    "userImg":"http://localhost:3000/imgs/avatar/avatar1.jpg",
    "userName":"月曜日",
    "content":'你是我活着的证明，带我一起探索人生的意义。',
    "Islike":false,
    "pv":{"id":297954,
          "pv":[
              {"title":'PV1',
                "url":'http://localhost:3000/video/不灭1.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN1.jpg'
              },
              {
                "title":'PV2',
                "url":'http://localhost:3000/video/不灭2.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN2.jpg'
              }
          ]
    }
  },
  {
    "id":316957,
    "cover":"http://localhost:3000/imgs/newRcom2_cover.webp",
    "title":'影宅',
    "tag1":"本质日常片",
    "tag2":"请开灯观看",
    "like":"73.7",
    "userImg":"http://localhost:3000/imgs/avatar/avatar2.jpg",
    "userName":"亮仔",
    "content":'“将头发梳成大人模样”// 对洁癖观众很不友好，精神摧残// 成长=逐步黑化// ED有点意思// 气氛和NeverLand太像了',
    "Islike":false,
    "pv":{"id":316957,
          "pv":[
              {"title":'正式PV',
                "url":'http://localhost:3000/video/影宅.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN3.jpg'
              }
          ]
    }
  },
  {
    "id":325286,
    "cover":"http://localhost:3000/imgs/newRcom3_cover.webp",
    "title":'Vivy -Fluorite Eye’s Song',
    "tag1":"原创动画",
    "tag2":"长月达平",
    "like":"88.7",
    "userImg":"http://localhost:3000/imgs/avatar/avatar3.jpg",
    "userName":"s1psw",
    "content":'萤石眼里的未来，也许就是各自怀揣着使命走向“正确”的终焉。',
    "Islike":false,
    "pv":{"id":325286,
          "pv":[
              {"title":'正式PV',
                "url":'http://localhost:3000/video/vivy4.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN4.jpg'
              },
              {"title":'概念PV01',
                "url":'http://localhost:3000/video/vivy1.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN5.jpg'
              },
              {"title":'概念PV02',
                "url":'http://localhost:3000/video/vivy2.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN5.jpg'
              },
              {"title":'概念PV03',
                "url":'http://localhost:3000/video/vivy3.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN5.jpg'
              }
          ]
    }
  },
  {
    "id":302189,
    "cover":"http://localhost:3000/imgs/newRcom4_cover.webp",
    "title":'86-不存在的战区-',
    "tag1":"白毛",
    "tag2":"网恋奔现",
    "like":"107.4",
    "userImg":"http://localhost:3000/imgs/avatar/avatar4.jpg",
    "userName":"月曜日",
    "content":'少女与泪水相伴，少年与死亡相随。原作第一卷质量过高，让人无比期待，加上强大动画制作阵容，使它成为了4月最受期待的动画之一。',
    "Islike":false,
    "pv":{"id":302189,
          "pv":[
              {"title":'PV1',
                "url":'http://localhost:3000/video/86-1.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN6.jpg'
              },
              {
                "title":'PV2',
                "url":'http://localhost:3000/video/86-2.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN7.jpg'
              }
          ]
    }
  },
  {
    "id":295048,
    "cover":"http://localhost:3000/imgs/newRcom5_cover.webp",
    "title":'美少年侦探团',
    "tag1":"乙女向",
    "tag2":"梦回樱兰",
    "like":"35.3",
    "userImg":"http://localhost:3000/imgs/avatar/avatar5.jpg",
    "userName":"椎名逐利",
    "content":'别的不说，作为老物语厨，看见新房昭之+西尾维新就已经可以打五星了。',
    "Islike":false,
    "pv":{"id":295048,
          "pv":[
              {"title":'PV1',
                "url":'http://localhost:3000/video/美少年1.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN8.jpg'
              },
              {
                "title":'PV2',
                "url":'http://localhost:3000/video/美少年2.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverN9.jpg'
              }
          ]
    }
  }
]
let oldRecom=[
  {
    "id":265,
    "cover":"http://localhost:3000/imgs/oldRcom1_cover.webp",
    "title":'新世纪福音战士',
    "tag1":"神棍",
    "tag2":"意识流",
    "like":"190",
    "userImg":"http://localhost:3000/imgs/avatar/avatar1.jpg",
    "userName":"思路乐悲",
    "content":'没有从EVA里看到过自己的人，你们是幸运的...',
    "Islike":false,
    "pv":{"id":265,
          "pv":[
              {"title":'预告PV1',
                "url":'http://localhost:3000/video/eva1.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO1.jpg'
              },
              {
                "title":'预告PV2',
                "url":'http://localhost:3000/video/eva2.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO2.jpg'
              },
              {
                "title":'预告PV3',
                "url":'http://localhost:3000/video/eva3.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO3.jpg'
              }
          ]
    }
  },
  {
    "id":9717,
    "cover":"http://localhost:3000/imgs/oldRcom2_cover.webp",
    "title":'魔法少女小圆',
    "tag1":"治愈",
    "tag2":"虚渊玄",
    "like":"224",
    "userImg":"http://localhost:3000/imgs/avatar/avatar2.jpg",
    "userName":"真武隐士",
    "content":'现代社会以印库贝塔的一句“和我签订契约，成为魔法少女吧”为嚆矢。滥觞传统魔法少女故事正失去它们的借鉴意义。',
    "Islike":false,
    "pv":{"id":9717,
          "pv":[
              {"title":'PV',
                "url":'http://localhost:3000/video/魔圆tv1.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO4.jpg'
              },
              {
                "title":'CM',
                "url":'http://localhost:3000/video/魔圆tv2.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO4.jpg'
              }
          ]
    }
  },
  {
    "id":18624,
    "cover":"http://localhost:3000/imgs/oldRcom3_cover.webp",
    "title":'回转企鹅罐',
    "tag1":"死妹控",
    "tag2":"生存战略",
    "like":"104",
    "userImg":"http://localhost:3000/imgs/avatar/avatar3.jpg",
    "userName":"晨夕踏雪",
    "content":'一起去品尝命运的果实吧！',
    "Islike":false,
    "pv":{"id":18624,
          "pv":[
              {"title":'PV1',
                "url":'http://localhost:3000/video/企鹅罐tv1.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              },
              {"title":'PV2',
                "url":'http://localhost:3000/video/企鹅罐tv2.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              },
              {"title":'PV3',
                "url":'http://localhost:3000/video/企鹅罐tv3.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              },
              {"title":'PV4',
                "url":'http://localhost:3000/video/企鹅罐tv4.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              },
              {"title":'PV5',
                "url":'http://localhost:3000/video/企鹅罐tv5.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              },
              {"title":'PV6',
                "url":'http://localhost:3000/video/企鹅罐tv6.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              },
              {"title":'PV7',
                "url":'http://localhost:3000/video/企鹅罐tv7.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              },
              {"title":'PV8',
                "url":'http://localhost:3000/video/企鹅罐tv8.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              },
              {"title":'PV9',
                "url":'http://localhost:3000/video/企鹅罐tv9.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              },
              {"title":'PV10',
                "url":'http://localhost:3000/video/企鹅罐tv10.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO5.jpg'
              }
          ]
    }
  },
  {
    "id":1420,
    "cover":"http://localhost:3000/imgs/oldRcom5_cover.webp",
    "title":'潘多拉之心',
    "tag1":"大腿兔",
    "tag2":"漫改",
    "like":"57.1",
    "userImg":"http://localhost:3000/imgs/avatar/avatar5.jpg",
    "userName":"蓬松蓬松",
    "content":'情怀加成下可以拉满（指漫画）…动画还行？',
    "Islike":false,
    "pv":{"id":1420,
          "pv":[
              {"title":'OP',
                "url":'http://localhost:3000/video/ph.mp4',
                "cover":'http://localhost:3000/imgs/pvCoverO6.jpg'
              }
          ]
    }
  }
]

module.exports={newRecom,oldRecom};